# Generated by Django 5.1.4 on 2024-12-10 15:54

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Meta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=200, verbose_name='Nome da Meta')),
                ('especifica', models.TextField(help_text='Descreva a meta de forma específica.', verbose_name='Específica')),
                ('mensuravel', models.TextField(help_text='Como você medirá o progresso?', verbose_name='Mensurável')),
                ('atingivel', models.TextField(help_text='Por que essa meta é realista?', verbose_name='Atingível')),
                ('relevante', models.TextField(help_text='Qual a importância dessa meta?', verbose_name='Relevante')),
                ('tempo', models.DateField(help_text='Data limite para alcançar a meta.', verbose_name='Data Final')),
                ('email', models.EmailField(help_text='Receberá o lembrete sobre a meta.', max_length=254, verbose_name='E-mail')),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
