# Generated by Django 5.1.4 on 2024-12-10 17:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='meta',
            name='email_enviado',
            field=models.BooleanField(default=False),
        ),
    ]
